### ISSUE TITLE
change README to suggest http vs kafka

### ISSUE THREAD

**Issue by adriancole** [Yelp/py_zipkin#11]
While Kafka is a great transport, it isn't the best one to start with. How about if we change the example in the README to use http?

We can of course say in prod you'd likely use Kafka, but suggesting http in the README will reduce time spent helping users get started in gitter.

cc @luukhoai who is trying to get started

**Comment by luukhoai** [comment]
Hi, please tell me how to use http instead of Kafka.
Thank you so much

**Comment by luukhoai** [comment]
Hi, 
There is one problem when I use Kafka 
**getaddrinfo failed for http://localhost:9411, exception was [Errno -2] Name or service not known. Is your advertised.host.name correct and resolvable?**

Please tell me, how to figure out it ? Thank you so much

**Comment by adriancole** [comment]
http://localhost:9411 is a zipkin server url (http).

Kafka is a different kind of server. Please wait for instructions on how to
use http, or use the scribe instructions I sent you earlier.
