### ISSUE TITLE
Release 1.0 version

### ISSUE THREAD

**Issue by drolando** [Yelp/py_zipkin#113]
We've been using py-zipkin in production for a while and we should release a 1.0 version at some point and start really following semver.

I'd like to get #111 merged and update the docs first though.

@bplotnick @adriancole is there anything else that should be fixed / added first?

**Comment by adriancole** [comment]
how about proto encoding?

**Comment by adriancole** [comment]
in the public api changing update_binary_annotations to update_tags and otherwise removing the notion of binary annotations from the public api surface (even if deprecated stuff remains)

**Comment by adriancole** [comment]
ship a default impl of HttpTransport which is pointed to the v2 url for json

**Comment by adriancole** [comment]
implement b3 single header format

**Comment by adriancole** [comment]
--EOF from adrian :D Nice job on this library!

**Comment by dmfallak** [comment]
We are now on v1.2.7.
