### ISSUE TITLE
V1 thrift encoding is 10x slower than V2 JSON

### ISSUE THREAD

**Issue by drolando** [Yelp/py_zipkin#119]
According to a small benchmark I wrote, encoding a span to `V1 thrift` takes **~100us** on average, while going to `V2 JSON` takes less than **10us**. `V1 JSON` is just 2x slower than `V2 JSON` at about 20us, which means the problem is not in the V1->V2 conversion.

I cProfiled that test and 85% of the time is spent inside `thriftpy2` encoding stuff to binary. Going back to an older version that used `thriftpy` showed very similar results.

I'm not sure there's much we can do to improve thriftpy's performance and since the thrift encoding is deprecated anyway I don't think it's worth spending too much time on it. I'll probably just document this and tell people to use json or protobuf when it'll be available.

It'd also be nice to have automated benchmarks that could detect performance regressions and help us tell people how long each operation takes on average.

**Comment by dmfallak** [comment]
V1_THRIFT encoding is now no longer supported (as of v1.2.7).
