### ISSUE TITLE
Im getting compilation error with <docker build> when RUN in Dockerfile RUN includes <pip3 install py-zipkin>

### ISSUE THREAD

**Issue by drfooser** [Yelp/py_zipkin#158]
On both CentOS7 and Ubuntu 20.04 (VBox guests on Windows 10) I get the same results when running <sudo docker build -t ....>. No error when I remove py-zipkin from the RUN line in Dockerfile. 

Sending build context to Docker daemon  6.656kB
Step 1/6 : FROM alpine:3.8
 ---> c8bccc0af957
Step 2/6 : RUN apk add --no-cache py3-pip python3 &&     pip3 install flask requests py-zipkin
 ---> Running in e335630fba53
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/11) Installing libbz2 (1.0.6-r7)
(2/11) Installing expat (2.2.8-r0)
(3/11) Installing libffi (3.2.1-r4)
(4/11) Installing gdbm (1.13-r1)
(5/11) Installing xz-libs (5.2.4-r0)
(6/11) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(7/11) Installing ncurses-terminfo (6.1_p20180818-r1)
(8/11) Installing ncurses-libs (6.1_p20180818-r1)
(9/11) Installing readline (7.0.003-r0)
(10/11) Installing sqlite-libs (3.25.3-r4)
(11/11) Installing python3 (3.6.9-r1)
Executing busybox-1.28.4-r3.trigger
OK: 67 MiB in 24 packages
Collecting flask
  Downloading https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8                                                                                                                                 e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl (94kB)
Collecting requests
  Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d                                                                                                                                 975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
Collecting py-zipkin
  Downloading https://files.pythonhosted.org/packages/a5/bd/a6b4531dc12078bf5d1c367caffa354e409cb7eda03d                                                                                                                                 c6d933493f85497d/py_zipkin-0.20.1-py2.py3-none-any.whl (52kB)

....
Then:

    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os                                                                                                                                  -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/py                                                                                                                                 thon3.6m -c thriftpy2/transport/cybase.c -o build/temp.linux-x86_64-3.6/thriftpy2/transport/cybase.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fdv_ssh5/thrif                                                                                                                                 tpy2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close()                                                                                                                                 ;exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-so4cab1b/install-record.txt --s                                                                                                                                 ingle-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-fdv_ssh5/thrift                                                                                                                                 py2/
You are using pip version 18.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c apk add --no-cache py3-pip python3 &&     pip3 install flask requests py-zipkin'                                                                                                                                  returned a non-zero code: 1

**Comment by drolando** [comment]
That's weird, py-zipkin is pure python so it shouldn't cause compile errors

**Comment by drolando** [comment]
It fails building thriftpy2. They only provide source tar.gz https://pypi.org/simple/thriftpy2/ , so you'll need to also install gcc and python-dev to be able to install it

**Comment by drfooser** [comment]
So my solution was to include apk add build-base python3-dev.
Thanks for your help.
