### ISSUE TITLE
Support 128-bit trace IDs

### ISSUE THREAD

**Issue by mjbryant** [Yelp/py_zipkin#28]
https://github.com/openzipkin/zipkin/releases/tag/1.14.4 added support for 128-bit trace IDs via a new `trace_id_high` field in the thrift schema. We'll have to update to support this use case.

**Comment by imcom** [comment]
Hi @mjbryant how is this going so far ? is there a schedule to add support of 128bit trace IDs ?

**Comment by mjbryant** [comment]
This likely isn't being worked on. @kaisen might have more context.

**Comment by bplotnick** [comment]
This was fixed in #36

**Comment by adriancole** [comment]
thanks!
