### ISSUE TITLE
Log 'sa' annotation for client spans

### ISSUE THREAD

**Issue by Coalla** [Yelp/py_zipkin#33]
This is from zipkin docs (http://zipkin.io/pages/data_model.html)
> spans that include cs can log an sa annotation of where they are going
> This helps when the destination protocol isn’t Zipkin instrumented, such as MySQL.

It seems that you can't log third-party server address using in such way. Please advise.

**Comment by adriancole** [comment]
ack; it doesn't look like this feature is in at the moment.

First, there'd need to be a hook for a user to indicate a client address (which is an endpoint aka host, so serviceName, ip, port where each field is optional).

ex. server_address(service_name, ipv4, port)

or.. address(SERVER_ADDR, service_name, ipv4, port)

there are only two address types, so either way is fine

That ends up in the span as a binary annotation of type bool (special case for "sa" and "ca")

something like this I guess..
```
endpoint = zipkin_core.Endpoint(
        ipv4=ipv4,
        port=port,
        service_name=service_name,
    )
ann_type = zipkin_core.AnnotationType.BOOL
create_binary_annotation("sa", 0x01, ann_type, endpoint)
```

mind you I'm rubbish in python, so help wanted :)

**Comment by dmitry-prokopchenkov** [comment]
Guys, would you mind if I create a pull request and add this ability by myself?

**Comment by kaisen** [comment]
you're welcome to do a PR for this, but i do have a branch in progress right now :)

**Comment by dmitry-prokopchenkov** [comment]
ok, this is not critical, I will try later
