### ISSUE TITLE
How can I create client root span?

### ISSUE THREAD

**Issue by dmitry-prokopchenkov** [Yelp/py_zipkin#35]
'sr' and 'ss' annotations are always added to root span in [logging_helper.py:150](https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/logging_helper.py#L150). It's not correctly for client root spans.

**Comment by adriancole** [comment]
sounds like a legit limitation in the current code.

**Comment by dmitry-prokopchenkov** [comment]
Guys, would you mind if I create a pull request and add this ability by myself?

**Comment by bplotnick** [comment]
@dmitry-prokopchenkov by all means!! We love pull requests! I'm actually not sure how this would look, so i'm interested to see what you might come up with 😄 . Let us know if you need a hand.

P.S. For some historical context, the reason this limitation exists is that py_zipkin was formed out of our initial project pyramid_zipkin, and in fact is still the main way we use py_zipkin. For us, everything starts with a service request. But I totally see why it would be useful to be able to start with a client span.

**Comment by dmitry-prokopchenkov** [comment]
ok, thanks, I will give it a try when I have some time

**Comment by bplotnick** [comment]
closed via #49

**Comment by kaisen** [comment]
@dmitry-prokopchenkov your change is included in the tagged v0.8.2 release :)

**Comment by dmitry-prokopchenkov** [comment]
@kaisen sorry, it was better to not change the release version, yes?

**Comment by bplotnick** [comment]
@dmitry-prokopchenkov i'm not sure what you're asking. are you talking about why we bumped the patch version rather than the minor version? we generally use semver at Yelp, but releases <1.0.0 have unstable APIs, so the usual semver rules are much looser and it's kind of a judgement call.

**Comment by kaisen** [comment]
@dmitry-prokopchenkov did you mean that it would have been better if you didn't change the release version in your PR? It doesn't matter to me :)

**Comment by dmitry-prokopchenkov** [comment]
@kaisen , @bplotnick ok, thanks for the explanations. I am looking forward for answer on my [question](https://github.com/Yelp/py_zipkin/issues/6#issuecomment-312414780) about batch span sending. This is that I might add quickly enough.
