### ISSUE TITLE
If your host can not be resolved by DNS, it will break tracing

### ISSUE THREAD

**Issue by dmitry-prokopchenkov** [Yelp/py_zipkin#37]
In some cases a machine host cannot be successfully resolved be DNS (for instance, dev machines weren't fully setup in my case). If your host is not resolvable, you will get an exception in  https://github.com/Yelp/py_zipkin/blob/master/py_zipkin/thrift/__init__.py#L64. This problem fully breaks tracing. I think this can be processed in more graceful way. May be it's better to log and swallow the exception and use the hostname as an endpoint. What do you think, guys?

**Comment by kaisen** [comment]
Note that #38 allows a workaround to avoid this issue. We still need to catch the exception and handle it gracefully though.
