### ISSUE TITLE
server send timings overstated

### ISSUE THREAD

**Issue by Jefftree** [Yelp/py_zipkin#42]
In a few zipkin traces, there were instances where server send was being emitted after client receive. It seems that "server send" represents the time when zipkin logging is finished (for a root span). However, a function being traced would already be completed when zipkin logging starts.

I believe the "server send" should be timestamped at the same time as `logging_start` since `logging_start` occurs when a function ends, and waiting until logging is completed would skew the timings (and make the span appear longer than the amount of time it actually took). We could potentially add a `logging_end` field to where the current "server send" is being logged.

**Comment by trtg** [comment]
:+1:  locally this issue didn't seem to be that huge, but now that i'm testing py_zipkin in a production/high-volume and distributed environment, the current duration of the root span is wildly overestimated (marked as >= 3 seconds) when all the nested spans only take up < 200ms. If I change ss to be logging_start, and duration to be logging_start - self.start_timestamp, the root span is only as wide as all the nested spans.
Also, this over estimate of duration happens every single time in production, it's not an occasional issue.

**Comment by kaisen** [comment]
@trtg fantastic, thanks for helping us confirm that this is an issue that needs to be addressed!

**Comment by bplotnick** [comment]
This is has been done since #47
