### ISSUE TITLE
Support sending spans in batches

### ISSUE THREAD

**Issue by mjbryant** [Yelp/py_zipkin#6]
The Zipkin Kafka collector supports receiving batches of spans instead of single spans after https://github.com/openzipkin/zipkin/pull/995. However, having a py_zipkin user implement batching solely in the transport_handler seems like it'd be too difficult on their part. 

Maybe we could support having `ZipkinLoggingContext` take a batch_size param that defaults to something large but sane (20?), then in [log_spans](https://github.com/Yelp/py_zipkin/blob/8c03eac8b0d49fa64d644bef62edbfc044078bb1/py_zipkin/logging_helper.py#L75) we could call transport_handler with a list of thrift-encoded spans as opposed to a single span at a time.

@kaisen, thoughts?

**Comment by dmitry-prokopchenkov** [comment]
@kaisen, @bplotnick What about this? AFAIK Zipkin serer can process batch spans. At least we might modify  [log_spans](https://github.com/Yelp/py_zipkin/blob/8c03eac8b0d49fa64d644bef62edbfc044078bb1/py_zipkin/logging_helper.py#L75) to send root span and self.log_handler.client_spans together. What do you think? I could give a try on this.

**Comment by dmitry-prokopchenkov** [comment]
@kaisen, @bplotnick Guys, your thoughts on this?

**Comment by bplotnick** [comment]
@dmitry-prokopchenkov Go for it!

You could make `log_span` just write to a queue and flush when it hits a configurable batch size (with a sane default). Then at the end of `log_spans`, you flush the queue to write the remaining spans.

**Comment by dmitry-prokopchenkov** [comment]
@bplotnick ok, thanks!

**Comment by dmitry-prokopchenkov** [comment]
@bplotnick just a reminder, this can be closed
