### ISSUE TITLE
No module named py_zipkin.transport (File missing)

### ISSUE THREAD

**Issue by fcribeiro** [Yelp/py_zipkin#83]
Hello, I wanted to use py_zipkin for my project but when I try to install it via pip install py_zipkin, the file "transport.py" seems to be missing, causing the "ModuleNotFoundError: No module named 'py_zipkin.transport'".
I was able to work arround this issue by installing the package manually but if I want to run my application using a docker container it will fail because of the same problem since the file transport.py will be missing when installing py_zipkin.

I am sorry if I did not describe this issue in the best way but I hope you could fix this so I could still use py_zipkin in my project.

**Comment by bplotnick** [comment]
@fcribeiro this is because the API changed a little bit from 0.11.0. If you look back in github to version 0.11.0, you'll see the docs for that version.

However, the real problem is that we forgot to upload the newest version to pypi! Sorry about that! I'll upload it now.

**Comment by fcribeiro** [comment]
Thanks! It is working now!

**Comment by bplotnick** [comment]
great! that was fast (I just uploaded 0.12.0 5 minutes ago!)

**Comment by fcribeiro** [comment]
I opened a new issue since I am new to py_zipkin and I would like to understand it better. Could you please help me? :)
