### ISSUE TITLE
How to check if there is an ongoing span before creating a new one?

### ISSUE THREAD

**Issue by fcribeiro** [Yelp/py_zipkin#85]
Hello, I would like to know how I could check if there is already a parent span created before I create a new one but I cannot find an example of that in the documentation.

Imagine I have a microservice A and B and a user makes a request for a function in A called function1 which then send a request for function2 in microservice B. I need to start a span on function1 and then I could use a decorator to trace that function2 on microservice B. What if a user calls for function2 in microservice B in the first place? 
I need to be able to start a span there but if I keep the annotation, when a user calls for function1 in microservice A, I will then have 2 different traces, one with 2 spans one nested into the other, and the other one with just 1 span from function2. I am not sure if I am explaining myself but in the end I would like a way to check if there is an ongoing trace and if so, a nested span is created, if not, a new trace needs to start.

**Comment by bplotnick** [comment]
Hrm. This is not usually something that we run into. What is the use-case?

It should be possible, though, by doing something like:

```python
from py_zipkin.stack import ThreadLocalStack
zipkin_attrs = ThreadLocalStack().get()
```

btw, i think you'll have better luck with questions like this in gitter (https://gitter.im/openzipkin/zipkin)

**Comment by fcribeiro** [comment]
Imagine I have a microservice that has a function that can list a user's songs and another microservice has a function that can list a user's playlists and that function will also send a request to the previous microservice to check all the songs info.
In this case if I start the span on the second microservice and then use the annotation on the first one, it will work since the end result would be a trace with 2 spans (the first span starting on the playlists and the second on the songs).
But if send a direct request to see a user's songs, if I only have the annotation there, it will not generate a span since a trace is not started yet. I am not sure if you can understand my problem but I will look into gitter. Thanks for the info!

**Comment by fcribeiro** [comment]
@zipkin_span(service_name='songs_ms', span_name='songs_controller.hello_world')`
def hello_world():
    with zipkin_span(
            service_name='songs_ms',
            span_name='songs_controller.hello_world',
            transport_handler=transport,
            port=5001,
            sample_rate=100,
    ):
        return RESP.response_200(message='Songs_MS working!')`

Imagine something like this, where if I send a direct request to this function it will generate a span that will be started in this exact function, but if there is a different microservice that will make a request on this function, it will generate 2 different traces, one trace with 2 spans, and one trace with 1 span that is created in this function.

**Comment by fcribeiro** [comment]
Thank you for your time, your solution works for me since I only need to check if there is a parent span already created or not. Sorry for the inconvenience I might have caused you and I thank you once again for your help and patience :smile:
