### ISSUE TITLE
README says use "Stack()" but Stack() needs one argument

### ISSUE THREAD

**Issue by siedentop** [Yelp/py_zipkin#95]
I am trying to use py-zipkin in a multi-threaded context. 

So, I followed the recommendation of the README. However, when running I get an exception because 'storage.Stack()' requires has the signature `def __init__(self, storage)`.

     context_stack = Stack() 
    TypeError: __init__() takes exactly 2 arguments (1 given)

Could you please update the README to work without workarounds?

**Comment by drolando** [comment]
Stack wants you to pass the storage as argument, so you should be using `Stack([])`. I've always found this confusing, so I'll change this to work similar to `SpanStorage`

**Comment by drolando** [comment]
Fixed by #118
